
If the grower had not participated in the experiment, the chosen strategy would have been to apply seed uniformly across the field at `r grower_chosen_rate_s` per acre.

The model predicts that this strategy was approximately _gc-opt-comp-txt-comes-here_.

For each zone, Figure \@ref(fig:status-quo-optimal-v) compares the per-acre net revenues that would have resulted from different management strategies. (Net revenues equal revenues from soybean sales minus seed costs.) For Zone 1, the model and data predicted net revenues of \$`r get_pi("gc", 1)` per acre if the field had been planted uniformly at the grower-chosen rate of grower_chosen_rate_hereK, and net revenues of \$`r get_pi("opt_v", 1)` had Zone 1 been planted at its estimated economically optimal rate of `r get_seed("opt_v", 1)`K. The two values \$`r get_pi("gc", 1)` and \$`r get_pi("opt_v", 1)` are shown by the red circles in the Zone 1's panel. Of course, as with any statistical data analysis, there cannot be 100% certainty that the actual net revenues from the two management plans would end up being exactly \$`r get_pi("gc", 1)` and \$`r get_pi("opt_v", 1)`. The black brackets centered over the red circles in the diagram show the ranges of net revenues that the data and model predict are “95% certain” to contain the true net revenues that would come about if the field trial were to be run again under the same weather conditions. A formal statistical test (called a t-test) established with a high level of statistical confidence that net revenues would indeed be greater at the `r get_seed("opt_v", 1)`K rate than at the grower-chosen rate of grower_chosen_rate_hereK (t = `r get_t_value(1)`).

For Zone 2, the net revenue is predicted to be \$`r get_pi("gc", 2)` per acre at the grower-chosen grower_chosen_rate_hereK seeds per acre, and \$`r get_pi("opt_v", 2)` at the zone-specific optimal seed rate of `r get_seed("opt_v", 2)`K per acre. _t-test-statement-for-zone-2_

For Zone 3, the net revenue is predicted to be \$`r get_pi("gc", 3)` per acre at the grower-chosen grower_chosen_rate_hereK seeds per acre, and \$`r get_pi("opt_v", 3)` at the zone-specific optimal seed rate of `r get_seed("opt_v", 3)`K per acre. _t-test-statement-for-zone-3_ 

```{r status-quo-optimal-v, fig.cap = "Confidence intervals of net revenues under grower-chosen (grower_chosen_rate_hereK) vs. optimal site-specific seeding strategies", fig.height = 4}

fig_data <- copy(opt_gc_data) %>% 
  .[, type_txt := case_when(
    type == "opt_v" ~ "optimal\nsite-specific\nrates",
    type == "gc" ~ "grower-\nchosen\n rate"
  )]

g_pi <- ggplot(data = fig_data) +
  geom_point(
    aes(
      y = profit_hat, 
      x = type_txt
    ), 
    size = 3, 
    color = "red"
  ) +
  geom_text(
    aes(
      y = max(fig_data$pi_upper) + 20, 
      x = type_txt,
      label = paste0("seed rate \n = ", round(seed_rate)) 
    ), 
    size = 4, 
    color = "blue"
  ) +
  # geom_text(
  #   data = pi_dif_test_zone,
  #   aes(
  #     y = max(fig_data$pi_upper) + 25, 
  #     x = "Optimal",
  #     label = paste0("(t = ", round(t, digits = 2), ")") 
  #   ), 
  #   size = 3, 
  #   color = "blue"
  # ) +
  geom_errorbar(
    aes(
    ymin = pi_lower, 
    ymax = pi_upper, 
    x = type_txt
    ),
    size = 1
  ) +
  facet_grid(. ~ zone_txt) +
  theme_bw() +
  ylim(NA, max(fig_data$pi_upper) + 30) +
  ylab("Net Revenue ($/acre)") +
  xlab("") +
  theme(
    axis.title.x = element_text(size = 12, vjust = -1),
    axis.title.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    strip.text = element_text(size = 12)
  ) +
  fig_theme_nonsp

g_pi

```

Figure \@ref(fig:whole-field-profit-comp) shows confidence intervals of the gains in net revenues achieved by changing management strategies across the whole field.  The data and model provide a point estimate of approximately \$`r whole_profits_test[type_short == "ovg", round(point_est_dif, digits = 0)]` per acre from implementing the recommended site-specific seeding strategy instead of the grower-chosen strategy of planting at grower_chosen_rate_hereK per acre everywhere on the field.  The confidence interval shows that the evidence that the site-specific strategy is more profitable than the grower-chosen strategy is extremely high.  The data and model also provide very strong evidence that the optimal variable rate strategy would result in greater profits than those from the optimal uniform rate strategy;  the point estimate of that profit difference is approximately \$`r whole_profits_test[type_short == "ovou", round(point_est_dif, digits = 0)]` per acre.  The third confidence interval in the figure shows that the data and model predict with over 95% confidence that the optimal uniform rate strategy of approximately `r round(unique(data_sf$opt_s_u), digits = 0)`K seeds per acre would lead to higher profits than would the grower-chosen strategy of grower_chosen_rate_hereK.  The point estimate of that profit difference is approximately \$`r whole_profits_test[type_short == "oug", round(point_est_dif, digits = 0)]`. 
