# Process the trial design in place of as-applied data

**Caution!**:

You are using the trial-design as the input data. Make sure you are okay with this!!!

```{r }
library(sf)
library(tidyverse)
library(data.table)
library(tmap)
library(measurements)
library(here)
```

## Read in datasets

```{r }
#--- trial design ---#
td_file_name <- list.files(recursive = TRUE) %>%
  .[str_detect(., "shp")] %>%
  .[!str_detect(., "xml")] %>%
  .[str_detect(., "trial-design")] 

td <- st_read(td_file_name) %>%
  st_transform_utm() %>%
  setnames(names(.), tolower(names(.)))

td_names <- names(td)
```

## Miscellaneous operations and various checks

### Change variable names

time variable needs to be dealt with separately

```{r }
dict_td <- dictionary[type == "trial_design", ]

td <- make_var_name_consistent(
    td, 
    dict_td 
  )
  
td <- setnames(td, "tgt_n", "n_rate")

td <- mutate(td, 
    n_rate = convert_N_unit(
      input_data_n$form, 
      input_data_n$unit, 
      n_rate, 
      field_data$reporting_unit
    ) + n_base_rate
  )
```

## Save the data

```{r }
here("Data/Growers", ffy, "Intermediate/as_applied_n.rds") %>% 
saveRDS(td, .)
```

