# Assign rates

## Assigning rates

```{r }

# trial_data_r$experiment_design
# trial_data_r$headland

#=== user-specified number of levels ===#
trial_data_r <- trial_data_eh %>% 
  mutate(num_levles = _num-levels-here_) %>% 
  mutate(rates = list(
    get_rates(
      min_rate = min_rate, 
      max_rate = max_rate, 
      gc_rate = gc_rate, 
      num_levels = num_levels
    )
  )) %>% 
  mutate(headland = list(
    mutate(headland, rate = gc_rate) %>% 
    dplyr::select(rate)
  )) %>% 
  mutate(experiment_design = list(
    assign_rates(
      data_sf = exp_plots, 
      rates_ls = rates,
      pattern = "fixed-latin-square"
    ) %>% 
    dplyr::select(rate)
  )) %>% 
  mutate(trial_design = list(
    rbind(
      experiment_design,
      headland
    ) %>% 
    setnames(
      "rate",
      case_when(
        form == "seed" ~ "tgts",
        form %in% c("uan28", "uan32", "urea") ~ "tgtn",
        #=== needs to change this ===#
        form == c("potash") ~ "tgtk"
      )
    ) %>% 
    st_transform(4326) 
  ))

``` 

# Save the trial design

```{r }
time_user <- paste0(
  Sys.time(), 
  "-",
  Sys.getenv("USER")
) %>% 
gsub(" ", "-", .) %>% 
gsub("_", "-", .)  

dsn_name <- here("Data", "Growers", ffy, "TrialDesign")

#=== write the trial design as a shape file ===#
st_write(
  trial_data_r$trial_design[[1]], 
  dsn = dsn_name,
  layer = paste0("trial-design-", time_user),
  driver = "ESRI Shapefile"
)

#=== write the ab-lines as a shape file ===#
st_write(
  trial_data_r$ab_lines[[1]], 
  dsn = dsn_name,
  layer = paste0("ab-lines-", time_user),
  driver = "ESRI Shapefile"
)

writeLines(
  paste0(
    "The trial design was named, trial-design-",
    time_user,
    ".shp"
  )
)
```

```{r }
trial_plot <- trial_data_r$trial_design[[1]] %>% 
  setnames(names(.)[1], "rate")
ab_line_plot <- trial_data_r$ab_lines[[1]] 

ggplot() +
  geom_sf(
    data = trial_plot, 
    aes(fill = factor(rate)),
    color = NA
  ) +
  scale_fill_brewer(palette = "Greens") + 
  geom_sf(
    data = ab_line_plot, 
    color = "red"
  ) 
 
```

# Orthogonality check

Checking if the assigned rates are orthogonal to the soil and field characteristics. 

```{r results = "hide", eval = F}

topo <- file.path(here("Data", "Growers", ffy), "Intermediate/topography.rds") %>% 
  readRDS()

ssurgo <- file.path(here("Data", "Growers", ffy), "Intermediate/ssurgo.rds") %>% 
  readRDS()

topo_values <- topo %>%
  stars_to_stack() %>%
  exact_extract(., st_transform(experiment_design, st_crs(.))) %>%
  rbindlist(idcol = "rowid") %>%
  .[,
    lapply(.SD, weighted.mean, w = coverage_fraction),
    by = rowid,
    .SDcols = paste0("layer.", 1:length(topo))
  ] %>%
  .[, rowid := NULL] %>%
  setnames(names(.), names(topo))

experiment_design <- cbind(experiment_design, topo_values)

ssurgo_values <- dplyr::select(experiment_design, cell_id) %>%
  st_intersection(., ssurgo) %>%
  mutate(area = as.numeric(st_area(.))) %>%
  data.table() %>%
  .[, area_pct := area / sum(area), by = cell_id] %>%
  .[,
    lapply(.SD, weighted.mean, w = area_pct),
    by = cell_id,
    .SDcols = c("clay", "sand", "silt", "water_storage")
  ]

experiment_design <- left_join(experiment_design, ssurgo_values, by = "cell_id")
  
```

```{r eval = F}
#--- plot level ---#
experiment_design %>% 
  dplyr::select(where(is.numeric)) %>% 
  st_drop_geometry() %>% 
  data.table() %>% 
  .[, lapply(.SD, mean), by = .(plot_id, strip_id)] %>% 
  .[,`:=`(
    plot_id = NULL,
    strip_id = NULL
  )] %>% 
  cor() %>% 
  .[, "rate"] 

#--- cell-level ---#
experiment_design %>% 
  dplyr::select(where(is.numeric)) %>% 
  st_drop_geometry() %>% 
  data.table() %>% 
  .[, cell_id := NULL] %>% 
  cor() %>% 
  .[, "rate"] 

```

