# Preparation for Creating Plots and ab-lines

## Set parameters

```{r }
side_plots_num <- _side-plots-num-here_ 
cell_height <- _cell-height-here_ 
head_dist <- _head-dist-here_
harvest_angle <- _harvest-angle-here_

```
## Read boundary and ab-line

```{r }
# ffy <- "Wendte_LaueLib80_2020"
# ffy <- "Boeckner_134n_2017"
# ffy <- "Bohnhoff_Adams_2018"
# ffy <- "Holzwart_Holzwart_2021"

#/*----------------------------------*/
#' ## field boundary
#/*----------------------------------*/
field_sf <- get_shp_name(ffy, "TrialDesign", "boundary") %>% 
  st_read() %>% 
  make_sf_utm()

field_bbox <- st_bbox(field_sf) 
field_len_ew <- field_bbox["xmax"] - field_bbox["xmin"]

#/*----------------------------------*/
#' ## Input ab-line
#/*----------------------------------*/
input_ab_line_files <- get_shp_name(ffy, "TrialDesign", "ab-line-i") 
past_input_files <- get_shp_name(ffy, "TrialDesign", "past-a-s|past-a-n|past-a-k") 

if (length(input_ab_line_files) > 0) {

  i_ab_line <- 
  input_ab_line_files[1] %>% 
  st_read() %>% 
  make_sf_utm() 

} else if (length(past_input_files) > 0) {

  i_ab_line <- 
  past_input_files[1] %>% 
  st_read() %>% 
  make_sf_utm() %>% 
  make_ab_line(field_sf) 
 
} else {

}

#=== make ab_line the width of the field ===#
i_ab_line <- 
st_extend_line(
  st_geometry(i_ab_line), 
  field_len_ew / as.numeric(st_length(i_ab_line))
)

#/*=================================================*/
#' # Harvester ab-line
#/*=================================================*/
if (harvest_angle == TRUE) {

  harvester_ab_line_files <- get_shp_name(ffy, "TrialDesign", "ab-line-h") 
  past_harvester_files <- get_shp_name(ffy, "TrialDesign", "past-a-h") 

  if (length(harvester_ab_line_files) > 0) {
    #=== use only the first one ===#
    h_ab_line <- 
    harvester_ab_line_files[1] %>% 
    st_read() %>% 
    make_sf_utm() 

  } else if (length(past_harvester_files) > 0) {

    h_ab_line <- 
    past_harvester_files[1] %>% 
    st_read() %>% 
    make_sf_utm() %>% 
    make_ab_line(field_sf)

    # ggplot() +
    #   geom_sf(data = h_ab_line, size = 2) +
    #   geom_sf(data = h_ab_line_2, color = "red") 
  } else {

    cat("No ab-line for harvest data or past harvest data files are available.")

  }

  harvest_angle <- get_h_angle(h_ab_line, i_ab_line)
    
} else {

  h_ab_line <- NULL

}

```

```{r }

if (length(h_ab_line) > 0) {
  #=== make ab_line the width of the field ===#
  h_ab_line <- 
  st_extend_line(
    st_geometry(h_ab_line), 
    field_len_ew / as.numeric(st_length(h_ab_line))
  )

  ab_lines_tmap <- c(i_ab_line, h_ab_line) %>% 
    st_as_sf() %>% 
    mutate(ab_id = c("input ab-line", "harvester ab-line"))

  ggplot() +
    geom_sf(data = field_sf) +
    geom_sf(data = ab_lines_tmap, aes(col = ab_id)) 

} else {

  ab_lines_tmap <- c(i_ab_line) %>% 
    st_as_sf() %>% 
    mutate(ab_id = "input ab-line")

  ggplot() +
    geom_sf(data = field_sf) +
    geom_sf(data = ab_lines_tmap, aes(col = ab_id))

}

```

## Option parameters

```{r }
trial_data_rh <- trial_data %>% 
  #=== headland length ===#
  # if only one number is supplied, it is applied for both inputs in a two-input case
  mutate(headland_length = conv_unit(head_dist, "ft", "m")) %>% 
  #=== cell height ===#
  mutate(cell_height = conv_unit(cell_height, "ft", "m")) %>% 
  #=== harvester angler ===#
  mutate(harvest_angle = harvest_angle) 

```

# Create Trial Design

## Make experiment grids

```{r }

#/*----------------------------------*/
#' ## Create experimental plots
#/*----------------------------------*/

num_unique_plot_width <- 
unique(trial_data_rh$input_plot_width) %>% 
length()

#=== get the first one of the two if more than one ===#
# input_plot_width <- trial_data_first$input_plot_width[[1]]
# machine_width <- trial_data_first$machine_width[[1]]
# headland_length <- trial_data_first$headland_length[[1]]
# harvest_angle <- trial_data_first$harvest_angle[[1]]

trial_data_first <- 
trial_data_rh[1, ] %>% 
mutate(line_edge_id = NA) %>% 
rowwise() %>% 
mutate(experiment_plots = list(
  make_trial_grids(
    field = field_sf, 
    #--- by default uses the first one ---#
    ab_line = i_ab_line[1, ], 
    plot_width = input_plot_width, 
    machine_width = machine_width, 
    cell_height = cell_height,
    headland_length = headland_length,
    harvest_angle = harvest_angle,
    side_plots_num = side_plots_num
  )
))

if (num_unique_plot_width == 1 & nrow(trial_data_rh) == 1) {

  trial_data_e <- trial_data_first 

} else if(num_unique_plot_width == 1 & nrow(trial_data_rh) == 2) {

  trial_data_second <- 
  trial_data_rh[2, ] %>% 
  mutate(experiment_plots = list(
    trial_data_first$experiment_plots[[1]]
  )) %>% 
  mutate(line_edge_id = NA)

  trial_data_e <- rbind(trial_data_first, trial_data_second)
  # trial_data_e$experiment_plots

} else {

  trial_data_second <- 
  trial_data_rh[2, ] %>% 
  slice(rep(1, 2)) %>% 
  mutate(line_edge_id = 1:2) %>% 
  rowwise() %>% 
  mutate(experiment_plots = list(
    make_trial_grids(
      field = field_sf, 
      #--- by default uses the first one ---#
      ab_line = trial_data_first$experiment_plots[[1]]$line_edges[line_edge_id, ], 
      plot_width = input_plot_width, 
      cell_height = cell_height,
      headland_length = headland_length,
      side_plots_num = side_plots_num,
      second_input = TRUE
    )   
  )) 

  trial_data_e <- rbind(trial_data_first, trial_data_second)

}

``` 

```{r }

trial_data_eh <-
trial_data_e %>% 
rowwise() %>% 
mutate(ab_lines = list(
  experiment_plots$ab_lines %>% 
    st_transform(4326)
)) %>% 
mutate(exp_plots = list(
  experiment_plots$exp_plots
)) %>% 
dplyr::select(- experiment_plots) %>% 
#=== dissolve the experimental plots as a single polygon ===#
mutate(experiment_plots_dissolved = list(
  exp_plots %>% 
    st_snap_to_grid(size = 0.0001) %>%
    st_make_valid() %>% 
    summarize(plot_id = min(plot_id)) 
)) %>% 
#=== Create headland ===#
# experiment_plots_dissolved <- trial_data_eh$experiment_plots_dissolved
# trial_data_eh$headland
mutate(headland = list(
  st_difference(field_sf, experiment_plots_dissolved) %>%
    st_as_sf() %>% 
    rename(., geometry = attr(., "sf_column")) %>% 
    dplyr::select(geometry)
)) %>% 
mutate(tm_exp_head = list(
  tm_shape(field_sf) +
    tm_borders(col = "black") + 
  tm_shape(headland) +
    tm_fill(
      col = "red", 
      alpha = 0.3, 
      title = "Headland"
    ) +
  tm_shape(exp_plots) +
    tm_fill(
      col = "strip_id", 
      palette = "Spectral", 
      style = "order"
    )  +
  tm_shape(field_sf) +
    tm_borders() +
  tm_layout_to_add 
))

```

```{r }
trial_data_eh$tm_exp_head

```

## Save experiment plots and headland

```{r }
saveRDS(
  trial_data_eh,
  here("Data", "Growers", ffy, "TrialDesign", "exp_plots.rds")
)  
```
