---
title: "Run Analysis for A crop-type-here Experiment"
output: html_document
---

# Preparation

## Set up

```{r setup, cache = F, echo = F}
library(knitr)
knitr::opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  error = TRUE,
  warning = FALSE,
  fig.retina = 6,
  message = FALSE
)

#--- working field-year ---#
ffy <- "field-year-here" 

#--- root directory ---#
opts_knit$set(root.dir = here("Data", "Growers", ffy))

#--- source functions ---#
source(
  "https://github.com/tmieno2/DIFM/blob/master/Functions/prepare.R?raw=TRUE",
  local = TRUE
)

```

## Packages

```{r pacakges, cache = FALSE}
# === packages ===#
library(sf)
library(tmap)
library(mgcv)
library(ggcorrplot)
library(patchwork)
library(scam)
library(parallel)
library(dplyr)
library(tidyverse)
library(corrplot)
library(data.table)
library(GWmodel)
library(mgcv)

```

```{r map-layout, cache = TRUE}
tm_layout_to_add <- tm_layout(
  legend.outside = "TRUE",
  frame = FALSE,
  legend.title.size = 2,
  legend.text.size = 1.5
)

```

## Field parameters

```{r }
#--- define field parameters ---#
# source(here("Codes/Functions/unpack_field_parameters.R"))
source(
  get_r_file_name("Functions/unpack_field_parameters.R"), 
  local = TRUE
)

```

# Seed analysis

```{r }
if (trial_type %in% c("SN", "S")) {
  get_r_file_name(
    "Analysis/a01_S_analysis.R",
    local = FALSE
  )
} else {
  cat("No seed analysis for this field") 
}

```


# Nitrogen analysis

```{r }
if (trial_type %in% c("SN", "N")) {
  get_r_file_name(
    "Analysis/a01_N_analysis.R",
    local = FALSE
  )
} else {
  cat("No nitrogen analysis for this field") 
}

```
