
# Rx data preparation

```{r }
Rx_s <- st_read(Rx_file_s) %>% 
  st_transform(st_crs(data)) %>%
  st_make_valid()

dict_yield <- dictionary[type == "Rx-s", ]
col_list <- dict_yield[, column]

Rx_s <- make_var_name_consistent(
  Rx_s, 
  dict_yield 
)

#--- seed rate conversion ---#
if (any(Rx_s$tgts > 10000)){
  #--- convert to K ---#
  Rx_s <- mutate(Rx_s, tgts = tgts / 1000)
}

```

```{r }
tm_shape(Rx_s) +
  tm_fill(col = "tgts")

```

# Identify grower-chosen rate

```{r }
obs_tgts <- st_intersection(data, Rx_s) %>% 
  mutate(area = as.numeric(st_area(.))) %>% 
  data.table() %>% 
  .[, .SD[area == max(area)], by = obs_id] %>% 
  .[, num_obs_per_zone := .N, tgts] %>% 
  .[, analyze := FALSE] %>% 
  .[num_obs_per_zone >= 200, analyze := TRUE] %>% 
  .[, .(obs_id, tgts, analyze)] 

data_dt <- obs_tgts[data.table(data), on = "obs_id"] 

```

# Analysis by Rx zone

```{r eval = (trial_type == "S"), echo = (trial_type == "S")}
#/*=================================================*/
#' # Analysis by zone
#/*=================================================*/ 

reg_data <- data_dt[analyze == TRUE, ] %>% 
  .[, tgts_txt := factor(tgts)]

gam_res <- gam(yield ~ s(seed_rate, k = 5, by = tgts_txt) + s(X) + s(Y) + te(X, Y), data = reg_data)

gc_data <- copy(reg_data) %>% 
  unique(by = "tgts_txt") %>% 
  setnames("tgts", "gc_rate") %>% 
  .[, .(gc_rate, tgts_txt)]

eval_data <- predict_yield_pi(
    data = reg_data, 
    est = gam_res, 
    var_name = "seed_rate", 
    gc_rate_data = gc_data,
    by = "tgts_txt"
  ) %>% 
  mutate(tgts = as.numeric(as.character(tgts_txt)))

opt_s_data <- eval_data %>% 
  .[, .SD[profit_hat == max(profit_hat), ] ,by = tgts_txt] %>% 
  setnames("seed_rate", "opt_s")

g_est_ys <- ggplot(eval_data) +
  geom_line(aes(y = yield_hat, x = seed_rate)) +
  geom_ribbon(
    aes(
      ymin = yield_hat - 1.96 * yield_hat_se, 
      ymax = yield_hat + 1.96 * yield_hat_se, 
      x = seed_rate
    ),
    fill = "red",
    alpha = 0.4
  ) +
  facet_grid(. ~ tgts_txt) +
  ylim(0, NA)

pi_dif_test <- get_dif_stat_zone(
  data = opt_s_data, 
  test_var = "seed_rate", 
  opt_var = "opt_s",
  gc_var = "tgts",
  gam_res = gam_res,
  by_var = "tgts_txt"
) 

#/*----------------------------------*/
#' ## dataset with optimal variable and uniform rates
#/*----------------------------------*/
data <- reg_data %>% 
  #--- merge with opt_s ---#
  .[opt_s_data[, .(opt_s, tgts)], on = "tgts"] %>% 
  #--- find optimal input (uniform) ---#
  .[, opt_s_u := find_opt_u(., "seed_rate", gam_res)]

```

```{r Estimated-yield-response-functions-by-zone}
g_est_ys   
```

# Whole-field profit tests

```{r }
whole_profits_test <- rbind(
  #--- opt (V) vs gc ---#
  get_dif_stat(
    data, 
    "seed_rate", 
    "opt_s", 
    "tgts",
    gam_res
  ) %>% 
  .[, type := "optimal site-specific rate strategy \n vs \n grower-chosen strategy"] %>% 
  .[, type_short := "ovg"],

  #--- opt (u) vs gc ---#
  get_dif_stat(
    data, 
    "seed_rate", 
    "opt_s", 
    "opt_s_u",
    gam_res
  ) %>% 
  .[, type := "optimal site-specific rate strategy \n vs \n optimal uniform rate strategy"] %>% 
  .[, type_short := "ovou"],

  #--- opt (u) vs gc ---#
  get_dif_stat(
    data, 
    "seed_rate", 
    "opt_s_u", 
    "tgts",
    gam_res
  ) %>% 
  .[, type := "optimal uniform rate strategy \n vs \n grower-chosen strategy"] %>% 
  .[, type_short := "oug"]
)
  
```

# Save the results

```{r }
results <- tibble(
  data_sf = list(st_as_sf(data)),
  eval_data = list(eval_data),
  opt_s_data = list(opt_s_data),
  pi_dif_test = list(pi_dif_test),
  whole_profits_test = list(whole_profits_test)
)  

saveRDS(results, here("Reports", "Growers", ffy, "analysis_results_Rx.rds"))
```

